[package]
name = "math"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
cgmath = { workspace = true }
ga_generator = "0.1.7"
serde = { workspace = true }

[lints]
workspace = true
