[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = { workspace = true }
eframe = { workspace = true }
math = { workspace = true }
rendering = { workspace = true }

[lints]
workspace = true
